name: بستنی فروشی منصور شعبه چهارراه گلوبندک

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: دانلود وانیل
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/CYBEREH/MyRAD/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/CYBEREH/MyRAD/main/wallpaper.png -OutFile wallpaper.bmp
        Invoke-WebRequest https://raw.githubusercontent.com/CYBEREH/MyRAD/main/wallpaper.bat -OutFile wallpaper.bat
    - name: زدن دستگاه به برق
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/CYBEREH/MyRAD/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/CYBEREH/MyRAD/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
    - name: ریختن وانیل تو دستگاه
      run: Expand-Archive ngrok.zip
    - name: آوردن دستگاه کارتخوان برای اینکه شما صد بکشی
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: بیرون کردن یکی از مشتری ها با پس گردنی و خالی کردن یک میز برای اینکه شما بشینی
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bmp D:\a\wallpaper.bmp
        copy wallpaper.bat D:\a\wallpaper.bat
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
    - name: از منظره زیبای چهار راه گلوبندک لذت ببرید
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: این هم قاشق اختصاصی شما برای اینکه بستنی وانیل خود را میل کنید. یکساعت وقت دارید که از محیط مفرح چهارراه گلوبندک استفاده کنید
      run: cmd /c start.bat
    - name: این صفحه را هم نبندید چونکه اقامت شما در چهارراه گلوبندک به آن وابسته است
      run: | 
        Invoke-WebRequest https://github.com/CYBEREH/MyRAD/raw/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
